### ISSUE TITLE
[Link Error] get_best_result_from_pinecorn() method is ouccred error using invaild link

### ISSUE THREAD

**Issue by gayakps** [sinanuozdemir/quick-start-guide-to-llms#19]
Hello I'm learnig llms student, I follow this examples and then study that but link error ouccred

I'm using this code

<code>
def get_best_result_from_pinecone(query, namespace=NAMESPACE):
    payload = json.dumps({
        "num_results": 2,
        "query": query,
        "re_ranking_strategy": "none",
        "namespace": namespace
    })

    response = requests.post(
        "https://information-retrieval-hiaa.onrender.com/document/retrieve",
        data=payload
    )

    # 디버깅을 위한 응답 상태 및 내용 출력
    print("Response status code:", response.status_code)
    print("Response JSON content:", response.json())

    # 응답이 성공적이고 documents 리스트가 비어있지 않은지 확인
    documents = response.json().get('documents', [])
    if not documents:
        raise ValueError("No documents found in the response.")

    return documents[0]
</code>

but this 'https://information-retrieval-hiaa.onrender.com/document/retrieve' link is show below that

![image](https://github.com/user-attachments/assets/7fbcd4c3-7219-470f-97d0-785feb616b5a)

**Comment by AAuhsoj** [comment]
I have the same problem.  :(

**Comment by sinanuozdemir** [comment]
Hey! Thanks so much for flagging this, I had to update the API to use some newer libraries. I'm a one person shop here maintaining this so your comments really help me get things moving. I'm now able to get results from the API here :) if you both see the same, I can close this!

The updated code for the API is here: https://github.com/sinanuozdemir/quick-start-llms-ir-fastapi

<img width="833" alt="Screenshot 2024-08-12 at 9 15 55 AM" src="https://github.com/user-attachments/assets/65c20182-a7e3-4e7b-b9d6-5a64edaf1a4f">

**Comment by AAuhsoj** [comment]
I really appreciate your quick response :) 

 I get the same result yours!! 
![image](https://github.com/user-attachments/assets/4846f564-8bf7-447a-87e5-65052bfe0e25)


---

The problem has been solved, unfortunately, URL you told about API responses 404 error
https://github.com/sinanuozdemir/quick-start-llms-ir-fastapi

![image](https://github.com/user-attachments/assets/501f9f96-1e4f-4d38-89af-a5dc785e0328)


If this problem is solved, I have no further comment on this issue.

Thanks you for your help and have a nice day!!

**Comment by gayakps** [comment]
Thanks !!

**Comment by sinanuozdemir** [comment]
Apologies! The url I meant to use was here in this repo: https://github.com/sinanuozdemir/quick-start-guide-to-llms/tree/main/semantic-search-fastapi

That one I gave is private because it's what I actually use for deployments :) just trying to keep some logical separation between educational code and real devops work.
